//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Depo_Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class DepoEntities4 : DbContext
    {
        public DepoEntities4()
            : base("name=DepoEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Malzeme> Malzemes { get; set; }
        public DbSet<Sektor> Sektors { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Teslimat> Teslimats { get; set; }
    
        public virtual ObjectResult<mbul_Result> mbul(string malzemeadi)
        {
            var malzemeadiParameter = malzemeadi != null ?
                new ObjectParameter("malzemeadi", malzemeadi) :
                new ObjectParameter("malzemeadi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<mbul_Result>("mbul", malzemeadiParameter);
        }
    
        public virtual int mekle(string malzemeadi, Nullable<int> malzemeadet, Nullable<decimal> malzemefiyat, string malzememarka, string malzememodel)
        {
            var malzemeadiParameter = malzemeadi != null ?
                new ObjectParameter("malzemeadi", malzemeadi) :
                new ObjectParameter("malzemeadi", typeof(string));
    
            var malzemeadetParameter = malzemeadet.HasValue ?
                new ObjectParameter("malzemeadet", malzemeadet) :
                new ObjectParameter("malzemeadet", typeof(int));
    
            var malzemefiyatParameter = malzemefiyat.HasValue ?
                new ObjectParameter("malzemefiyat", malzemefiyat) :
                new ObjectParameter("malzemefiyat", typeof(decimal));
    
            var malzememarkaParameter = malzememarka != null ?
                new ObjectParameter("malzememarka", malzememarka) :
                new ObjectParameter("malzememarka", typeof(string));
    
            var malzememodelParameter = malzememodel != null ?
                new ObjectParameter("malzememodel", malzememodel) :
                new ObjectParameter("malzememodel", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("mekle", malzemeadiParameter, malzemeadetParameter, malzemefiyatParameter, malzememarkaParameter, malzememodelParameter);
        }
    
        public virtual int mguncelle(Nullable<int> malzemeno, string malzemeadi, Nullable<int> malzemeadet, Nullable<decimal> malzemefiyat, string malzememarka, string malzememodel)
        {
            var malzemenoParameter = malzemeno.HasValue ?
                new ObjectParameter("malzemeno", malzemeno) :
                new ObjectParameter("malzemeno", typeof(int));
    
            var malzemeadiParameter = malzemeadi != null ?
                new ObjectParameter("malzemeadi", malzemeadi) :
                new ObjectParameter("malzemeadi", typeof(string));
    
            var malzemeadetParameter = malzemeadet.HasValue ?
                new ObjectParameter("malzemeadet", malzemeadet) :
                new ObjectParameter("malzemeadet", typeof(int));
    
            var malzemefiyatParameter = malzemefiyat.HasValue ?
                new ObjectParameter("malzemefiyat", malzemefiyat) :
                new ObjectParameter("malzemefiyat", typeof(decimal));
    
            var malzememarkaParameter = malzememarka != null ?
                new ObjectParameter("malzememarka", malzememarka) :
                new ObjectParameter("malzememarka", typeof(string));
    
            var malzememodelParameter = malzememodel != null ?
                new ObjectParameter("malzememodel", malzememodel) :
                new ObjectParameter("malzememodel", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("mguncelle", malzemenoParameter, malzemeadiParameter, malzemeadetParameter, malzemefiyatParameter, malzememarkaParameter, malzememodelParameter);
        }
    
        public virtual ObjectResult<mlistele_Result> mlistele()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<mlistele_Result>("mlistele");
        }
    
        public virtual int msil(Nullable<int> malzemeno)
        {
            var malzemenoParameter = malzemeno.HasValue ?
                new ObjectParameter("malzemeno", malzemeno) :
                new ObjectParameter("malzemeno", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("msil", malzemenoParameter);
        }
    
        public virtual ObjectResult<sbul_Result> sbul(string sektoradi)
        {
            var sektoradiParameter = sektoradi != null ?
                new ObjectParameter("sektoradi", sektoradi) :
                new ObjectParameter("sektoradi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sbul_Result>("sbul", sektoradiParameter);
        }
    
        public virtual int sekle(string sektoradi, string sektorfaaliyetyil, string sektoraciklama, Nullable<int> malzemeno)
        {
            var sektoradiParameter = sektoradi != null ?
                new ObjectParameter("sektoradi", sektoradi) :
                new ObjectParameter("sektoradi", typeof(string));
    
            var sektorfaaliyetyilParameter = sektorfaaliyetyil != null ?
                new ObjectParameter("sektorfaaliyetyil", sektorfaaliyetyil) :
                new ObjectParameter("sektorfaaliyetyil", typeof(string));
    
            var sektoraciklamaParameter = sektoraciklama != null ?
                new ObjectParameter("sektoraciklama", sektoraciklama) :
                new ObjectParameter("sektoraciklama", typeof(string));
    
            var malzemenoParameter = malzemeno.HasValue ?
                new ObjectParameter("malzemeno", malzemeno) :
                new ObjectParameter("malzemeno", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sekle", sektoradiParameter, sektorfaaliyetyilParameter, sektoraciklamaParameter, malzemenoParameter);
        }
    
        public virtual int sguncelle(Nullable<int> sektorno, string sektoradi, string sektorfaaliyetyil, string sektoraciklama, Nullable<int> malzemeno)
        {
            var sektornoParameter = sektorno.HasValue ?
                new ObjectParameter("sektorno", sektorno) :
                new ObjectParameter("sektorno", typeof(int));
    
            var sektoradiParameter = sektoradi != null ?
                new ObjectParameter("sektoradi", sektoradi) :
                new ObjectParameter("sektoradi", typeof(string));
    
            var sektorfaaliyetyilParameter = sektorfaaliyetyil != null ?
                new ObjectParameter("sektorfaaliyetyil", sektorfaaliyetyil) :
                new ObjectParameter("sektorfaaliyetyil", typeof(string));
    
            var sektoraciklamaParameter = sektoraciklama != null ?
                new ObjectParameter("sektoraciklama", sektoraciklama) :
                new ObjectParameter("sektoraciklama", typeof(string));
    
            var malzemenoParameter = malzemeno.HasValue ?
                new ObjectParameter("malzemeno", malzemeno) :
                new ObjectParameter("malzemeno", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sguncelle", sektornoParameter, sektoradiParameter, sektorfaaliyetyilParameter, sektoraciklamaParameter, malzemenoParameter);
        }
    
        public virtual ObjectResult<slistele_Result> slistele()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<slistele_Result>("slistele");
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int ssil(Nullable<int> sektorno)
        {
            var sektornoParameter = sektorno.HasValue ?
                new ObjectParameter("sektorno", sektorno) :
                new ObjectParameter("sektorno", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ssil", sektornoParameter);
        }
    
        public virtual ObjectResult<tbul_Result> tbul(string teslimatadi)
        {
            var teslimatadiParameter = teslimatadi != null ?
                new ObjectParameter("teslimatadi", teslimatadi) :
                new ObjectParameter("teslimatadi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbul_Result>("tbul", teslimatadiParameter);
        }
    
        public virtual int tekle(string teslimatadi, string teslimatadres, Nullable<decimal> ucret, Nullable<int> sektorno)
        {
            var teslimatadiParameter = teslimatadi != null ?
                new ObjectParameter("teslimatadi", teslimatadi) :
                new ObjectParameter("teslimatadi", typeof(string));
    
            var teslimatadresParameter = teslimatadres != null ?
                new ObjectParameter("teslimatadres", teslimatadres) :
                new ObjectParameter("teslimatadres", typeof(string));
    
            var ucretParameter = ucret.HasValue ?
                new ObjectParameter("ucret", ucret) :
                new ObjectParameter("ucret", typeof(decimal));
    
            var sektornoParameter = sektorno.HasValue ?
                new ObjectParameter("sektorno", sektorno) :
                new ObjectParameter("sektorno", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("tekle", teslimatadiParameter, teslimatadresParameter, ucretParameter, sektornoParameter);
        }
    
        public virtual int tguncelle(Nullable<int> teslimatno, string teslimatadi, string teslimatadres, Nullable<decimal> ucret, Nullable<int> sektorno)
        {
            var teslimatnoParameter = teslimatno.HasValue ?
                new ObjectParameter("teslimatno", teslimatno) :
                new ObjectParameter("teslimatno", typeof(int));
    
            var teslimatadiParameter = teslimatadi != null ?
                new ObjectParameter("teslimatadi", teslimatadi) :
                new ObjectParameter("teslimatadi", typeof(string));
    
            var teslimatadresParameter = teslimatadres != null ?
                new ObjectParameter("teslimatadres", teslimatadres) :
                new ObjectParameter("teslimatadres", typeof(string));
    
            var ucretParameter = ucret.HasValue ?
                new ObjectParameter("ucret", ucret) :
                new ObjectParameter("ucret", typeof(decimal));
    
            var sektornoParameter = sektorno.HasValue ?
                new ObjectParameter("sektorno", sektorno) :
                new ObjectParameter("sektorno", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("tguncelle", teslimatnoParameter, teslimatadiParameter, teslimatadresParameter, ucretParameter, sektornoParameter);
        }
    
        public virtual ObjectResult<tlistele_Result> tlistele()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tlistele_Result>("tlistele");
        }
    
        public virtual int tsil(Nullable<int> teslimatno)
        {
            var teslimatnoParameter = teslimatno.HasValue ?
                new ObjectParameter("teslimatno", teslimatno) :
                new ObjectParameter("teslimatno", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("tsil", teslimatnoParameter);
        }
    }
}
