//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Depo_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Malzeme
    {
        public Malzeme()
        {
            this.Sektors = new HashSet<Sektor>();
        }
    
        public int malzemeno { get; set; }
        public string malzemeadi { get; set; }
        public Nullable<int> malzemeadet { get; set; }
        public Nullable<decimal> malzemefiyat { get; set; }
        public string malzememarka { get; set; }
        public string malzememodel { get; set; }
    
        public virtual ICollection<Sektor> Sektors { get; set; }
    }
}
